[rclone]
dest = ""

[rabbitmq]

  [rabbitmq.inbound]
  hostname = "localhost"
  port = "5672"
  username = "guest"
  password = "guest"
  vhost = "/"
  exchange = "kanchi"
  routingKey = ""
  queue = "kanchi-rss"

  [rabbitmq.outbound]
  hostname = "localhost"
  port = "5672"
  username = "guest"
  password = "guest"
  vhost = "/"
  exchange = "reina"
  routingKey = ""
  queue = "reina-dl"